MvcMusicStore/Controllers/ShippingController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using MvcMusicStore.Models;
using ShipmentService.Commands;

namespace MvcMusicStore.Controllers
{
    [Authorize]
    public class ShippingController : Controller
    {
        // GET: /Shipping
        public ActionResult Index(string orderId, string amount)
        {
            ViewBag.OrderId = orderId;
            ViewBag.Amount = amount;
            return View();
        }

        // POST: /Shipping/Address
        [HttpPost]
        public ActionResult Address(FormCollection values)
        {
            var shippingAddress = new ShippingAddress();
            TryUpdateModel(shippingAddress);

            var orderId = values["OrderId"];
            var amount = values["Amount"];

            MvcApplication.Bus.Send<ShipToCommand>(c =>
                                                       {
                                                           c.OrderId = orderId;
                                                           c.Name = shippingAddress.FirstName + " " + shippingAddress.LastName;
                                                           c.Address = shippingAddress.Address;
                                                           c.Zip = shippingAddress.PostalCode;
                                                           c.City = shippingAddress.City;
                                                       });


            return RedirectToAction("Index", "Payment", new {orderId, amount });

        }
    }
}

MvcMusicStore/Views/Shipping/Index.cshtml
@model MvcMusicStore.Models.ShippingAddress

@{
    ViewBag.Title = "Address";
}

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm("Address", "Shipping")) {
    
    <h2>Shipping</h2>
    <fieldset>
        <legend>Shipping Information for order @ViewBag.OrderId of cost @ViewBag.Amount</legend>

        @Html.EditorForModel()
        @Html.Hidden("OrderId", (string)ViewBag.OrderId)
        @Html.Hidden("Amount", (string)ViewBag.Amount)
    </fieldset>
    <input type="submit" value="Continue to payment" />
}