MvcMusicStore/Controllers/ShoppingCartController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using MvcMusicStore.Models;
using MvcMusicStore.ViewModels;
using ShoppingCartService.Commands;

namespace MvcMusicStore.Controllers
{
    public class ShoppingCartController : Controller
    {
        MusicStoreEntities storeDB = new MusicStoreEntities();

        //
        // GET: /ShoppingCart/

        public ActionResult Index()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Set up our ViewModel
            var viewModel = new ShoppingCartViewModel
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal()
            };

            // Return the view
            return View(viewModel);
        }

        //
        // GET: /Store/AddToCart/5

        public ActionResult AddToCart(int id)
        {

            // Retrieve the album from the database
            var addedAlbum = storeDB.Albums
                .Single(album => album.AlbumId == id);

            // Add it to the shopping cart
            var cart = ShoppingCart.GetCart(this.HttpContext);

            cart.AddToCart(addedAlbum);

            // Go back to the main store page for more shopping
            return RedirectToAction("Index");
        }

        //
        // AJAX: /ShoppingCart/RemoveFromCart/5

        [HttpPost]
        public ActionResult RemoveFromCart(int id)
        {
            // Remove the item from the cart
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Get the name of the album to display confirmation
            string albumName = storeDB.Carts
                .Single(item => item.RecordId == id).Album.Title;

            // Remove from cart
            int itemCount = cart.RemoveFromCart(id);

            // Display the confirmation message
            var results = new ShoppingCartRemoveViewModel
            {
                Message = Server.HtmlEncode(albumName) +
                    " has been removed from your shopping cart.",
                CartTotal = cart.GetTotal(),
                CartCount = cart.GetCount(),
                ItemCount = itemCount,
                DeleteId = id
            };

            return Json(results);
        }

        //
        // Get: /ShoppingCart/Checkout
        [HttpGet]
        public ActionResult Checkout()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);
            if (cart != null)
            {

                var orderId = Guid.NewGuid().ToString();
                var total = cart.GetTotal();
                MvcApplication.Bus.Send<CreatOrderCommand>(c =>
                                                               {
                                                                   c.OrderId = orderId;
                                                                   c.User = User.Identity.Name;
                                                                   c.CartItems = (from ci in cart.GetCartItems()
                                                                                  select new CreatOrderCommand.CartItem
                                                                                             {
                                                                                                 AlbumId = ci.AlbumId,
                                                                                                 Price = ci.Album.Price
                                                                                             }).ToList();
                                                               });
                cart.EmptyCart();
                return RedirectToAction("Index", "Shipping", new { orderId = orderId , amount = total});
            }
            return View("Index");
        }

        //
        // GET: /ShoppingCart/CartSummary

        [ChildActionOnly]
        public ActionResult CartSummary()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            ViewData["CartCount"] = cart.GetCount();

            return PartialView("CartSummary");
        }
    }
}

MvcMusicStore/Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcMusicStore.Models;

namespace MvcMusicStore.Controllers
{
    public class StoreController : Controller
    {
        MusicStoreEntities storeDB = new MusicStoreEntities();

        //
        // GET: /Store/

        public ActionResult Index()
        {
            var genres = storeDB.Genres.ToList();

            return View(genres);
        }

        //
        // GET: /Store/Browse?genre=Disco

        public ActionResult Browse(string genre)
        {
            // Retrieve Genre and its Associated Albums from database
            var genreModel = storeDB.Genres.Include("Albums")
                .Single(g => g.Name == genre);

            return View(genreModel);
        }

        //
        // GET: /Store/Details/5

        public ActionResult Details(int id)
        {
            var album = storeDB.Albums.Find(id);

            return View(album);
        }

        //
        // GET: /Store/GenreMenu

        [ChildActionOnly]
        public ActionResult GenreMenu()
        {
            var genres = storeDB.Genres.ToList();

            return PartialView(genres);
        }

    }
}

MvcMusicStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/jquery-1.6.4.min.js" type="text/javascript"></script>
</head>
<body>         
    <div id="header">
        <h1><a href="/">ASP.NET MVC MUSIC STORE</a></h1>
        <ul id="navlist">
            <li class="first"><a href="@Url.Content("~")" id="current">Home</a></li>
            <li><a href="@Url.Content("~/Store/")">Store</a></li>
            <li>@{Html.RenderAction("CartSummary", "ShoppingCart");}</li>
            <li><a href="@Url.Content("~/StoreManager/")">Admin</a></li>
        </ul>        
    </div>
        
    @{Html.RenderAction("GenreMenu", "Store");}

    <div id="main">
        @RenderBody()
    </div>

    <div id="footer">built with <a href="http://asp.net/mvc">ASP.NET MVC 4</a>
    </div>
</body>
</html>

MvcMusicStore/Views/Shared/_Layout.mobile.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" type="text/css" href="~/Content/jquery.mobile-1.1.0.css" />
    <script src="~/Scripts/jquery-1.6.4.min.js" type="text/javascript"></script>
    <script>
        $(document).bind("mobileinit", function () {
            //$.mobile.ajaxEnabled = false;
        });
    </script>
    <script type="text/javascript" src="~/Scripts/jquery.mobile-1.1.0.js"></script>
    <script>

        $("#Store").live("pageinit", function () {
            $(this).bind("swipeleft", function () {
                $("#genrelist").append($("<li>swipeleft</li>"))
                               .listview("refresh");
            });
        });

    </script>
</head>
<body>
        <div data-role="page" id="@ViewBag.PageId">
    
        <div id="header" data-role="header">
            <h1>MVC MUSIC</h1>
            <a href="@Url.Content("~/")" data-icon="home" data-iconpos="notext">Home</a>
            <a href="@Url.Action("About", "Home")" data-icon="info" data-iconpos="notext" data-rel="dialog">About</a>
            <div data-role="navbar">
                <ul id="navlist">
                    <li class="first"><a href="@Url.Content("~")" id="current">Home</a></li>
                    <li><a href="@Url.Content("~/Store/")">Store</a></li>
                    <li>
                        @{Html.RenderAction("CartSummary", "ShoppingCart");}
                    </li>
                </ul>
            </div>
        </div>

        <div id="main" data-role="content">
            @RenderBody()
        </div>

        <div id="footer" data-role="footer">
            <h1>built with <a href="http://asp.net/mvc" data-ajax="false">ASP.NET MVC 4</a></h1>
        </div>
    </div>
</body>
</html>